config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth', registrations: 'users/registrations' }
  devise_scope :user do
    match '/session/user', to: 'devise/sessions#create', via: :post
    match '/users/sign_up', to: 'devise/registrations#create', via: :post
    root to: "devise/sessions#new"
  end
  resources :users do
    resources :homes do
      resources :lists do
        resources :items
      end
    end
  end
  resources :homes
  resources :lists do
    resources :items
  end
  resources :homes do
    resources :bridges
  end
  resources :bridges do
    resources :groups do
      resources :scenes
    end
  end
  resources :groups do
    resources :scenes
  end
  resources :scenes
  resources :users do
    resources :homes do
      resources :pets
    end
  end
  resources :pets
  resources :static
  resources :admin, only: [:index]
  get '/logout', to: 'remove#destroy'
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :home
  has_many :items
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def new
    @list = List.new
    @lists = List.all
    @home = Home.find(params[:home_id])
  end

  def show
    @home = Home.find(params[:home_id])
    @list = List.find(params[:id])
    @item = Item.new
  end

  def edit
    @user = current_user
    @home = Home.find(params[:home_id])
    @list = List.find(params[:id])
    @new_item = Item.new
  end

  def index
    @user = current_user
    @home = Home.find(params[:home_id])
    @new_list = List.new
    @new_item = Item.new
  end

  def update
    @user = current_user
    @list = List.find(params[:id])
    @home = Home.find(@list.home_id)
    @list.update(list_params)
    @new_list = List.new
    redirect_to user_home_lists_path(current_user, @home.id)
  end

  def create
    @list = List.new(list_params)
    @user = current_user
    @home = Home.find(params[:home_id])
    @new_list = List.new
    if @list.save!
      @lists = List.all
      render :index
    else
      render :index
    end
  end

  def destroy
    list = List.find(params[:id])
    home_id = list.home_id
    list.destroy
    redirect_to user_home_lists_path(current_user, home_id)
  end
  private

  def list_params # strong parameters
    params.require(:list).permit(:name, :home_id)
  end
end

app/helpers/lists_helper.rb
module ListsHelper

  def create_list_widget(home)
    @home = Home.find(home)
    @home.lists.build(name: "")
    @home.save
  end

end

app/views/lists/_existing_lists.html.erb
      <div class="card-body">
        <div class="table-responsive">
          <table class="table-hover table-striped">
            <thead class="text-primary">
            <th scope="col">Name</th>
            <th scope="col"></th>
            <th scope="col"></th>
            <th scope="col"></th>
            <th scope="col">Item Count</th>
            <th scope="col">Color</th>
            <th scope="col">Remove</th>
            </thead>
            <tbody>
            <% @home.lists.each do |list| %>
              <tr>
                <%= form_for [list] do |f| %>
                  <td colspan="4">
                    <div class="row">
                    <div class="col-md-6 col-sm-6">
                    <%= f.hidden_field :home_id, value: "#{@home.id}"  %>
                    <%= f.text_field :name, class: "form-control", :required => true, placeholder: "List Name" %>
                    </div>
                    <div class="col-md-6 col-sm-6">
                    <%= f.submit "Update Name", class: "btn btn-sm btn-primary pull-right" %>
                    </div>
                    </div>
                    <div class="clearfix"></div>
                  <% end %>
                  </td>
                <td><%= list.items.count %></td>
                <td></td>
                <td><%= button_to "Delete", list, method: :delete, data: { confirm: "Are you sure? This cannot be undone." }, class: "btn btn-sm btn-danger"%></td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div><br><br>

app/views/lists/_form.html.erb
<div class="col-md-12">
    <div class="card">
      <div class="card-header card-header-tabs card-header-success">
        <div class="nav-tabs-navigation">
          <div class="nav-tabs-wrapper">
          <span class="nav-tabs-title"><%= @list.name %>
            <% if @list.name == "" %>
               <% name = "Default List"  %>
              <%= name %>
              <% end %>
          </span>
          </div>
        </div>
      </div>
      <div class="row justify-content-center">
        <div class="col-md-8">
          <div class="form-group">
            <% if @list.name == "" %>
              <h4 class="text-center"><%= 'This is a default list created for you, you should' %>
                <%= link_to "change the name" + '.', edit_user_home_list_path(@user, @home, @list), data: { turbolinks: 'false' } %>
              </h4>
            <% end %>
            <%= form_for [@user, @home, @list, @new_item], remote: true do |f| %>
              <%= f.text_field :description, :class => "form-control text-center", :placeholder => (@new_item.errors.full_messages_for(:description).first || "Enter a new item..."), id: "addItem" %>
              <%= f.submit :style => "display: none", data: { disable_with: "Please wait..."} %>

            <% end %>
          </div>
        </div>
      </div>
      <div class="card-body">
        <div class="tab-content">
          <div class="tab-pane active" id="LISTNAME">
            <table class="table">
              <tbody>
              <% @list.items.each do |item| %>
                <tr>
                  <td>
                    <div class="form-check">
                      <%= form_for [@list, item], remote: true do |f| %>
                        <div class="row">
                          <div class="col-md-12">
                            <%= f.check_box :status, :checked => (true if item.complete?) %>
                            <%= f.label item.description, id: "strikethrough" %>
                            <%= f.submit :style => "display: none", data: { disable_with: "Please wait..."} %>
                          </div>
                        </div>
                      <% end %>
                    </div>
                  </td>
                  <td class="td-actions">
                    <%= form_for [@list, item], method: :delete, remote: true do |f| %>
                      <button type="submit" rel="tooltip" class="btn btn-danger btn-link btn-sm">
                        <i class="material-icons">close</i>
                      </button>
                    <% end %>
                  </td>
                </tr>
              <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/lists/_new_form.html.erb
<div class="card-body">
  <%= form_for [@user, @home, @new_list] do |f| %>
    <div class="row">
      <div class="col-md-12">
        <div class="form-group">
          <%= f.hidden_field :home_id, value: "#{@home.id}"  %>
          <%= f.label :name, "List Name", class: "bmd-label-floating" %>
          <%= f.text_field :name, class: "form-control", :required => true, placeholder: 'ex. "Grocery List", "To-Do"' %>
          <br>
          <%= f.submit "Create a New List", class: "btn btn-primary pull-right" %>
        </div>
      </div>
    </div>
    <div class="clearfix"></div>
  <% end %>
  <br>
</div>

app/views/lists/edit.html.erb
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header card-header-primary">
            <h3 class="card-title">Edit List</h3>
          </div>
          <div class="card-body">
            <%= form_for [@user, @home, @list] do |f| %>
              <div class="row">
                <div class="col-md-12">
                  <div class="form-group">
                    <%= f.hidden_field :home_id, value: "#{@home.id}"  %>
                    <%= f.label :name, "List Name", class: "bmd-label-floating" %>
                    <%= f.text_field :name, class: "form-control", :required => true %>
                  </div>
                </div>
              </div>
              <%= f.submit "Update Name", class: "btn btn-primary pull-right" %>
              <div class="clearfix"></div>
            <% end %>
          </div>
          <br><br>
    <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/lists/index.html.erb
<div class="content">
  <div class="container-fluid">
    <a href="javascript:history.back()">< Return to Previous Page</a>
    <div class="row">
      <div class="col-md-8 col-lg-8 col-centered">
        <div class="card">
          <div class="card-header card-header-primary">
            <h3 class="card-title ">Existing Lists</h3>
            <h5>Rename or delete your existing lists here.</h5>
          </div>
          <% if @home.lists.count != 0 %>
            <%= render 'existing_lists' %>
            <% else %>
            <br>
            <div class="card-body">
            <h4>You don't have any lists, create one below!</h4>
            </div>
            <br>
          <% end %>
          <div class="card-header card-header-success">
            <h3 class="card-title">Create a New List</h3>
          </div>
          <div class="card-body">
          <h5 class="text-warning">Create additional lists here. There is no limit to the amount of lists you can create.</h5>
            <br>
            <p class="text-success text-center"><i>Remember to complete tasks on your lists so things don't get out of control!</i></p>
          </div>
          <%= render 'new_form' %>
          <div class="card-body">
            <div class="row pull-right">
          <%= button_to "Return to Dashboard", user_home_path(current_user, @home), method: :get, class: "btn pull-right", style: "background-color: yellow;" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/lists/new.html.erb
<%= render 'form' %>

app/views/lists/show.html.erb
<div class="col-md-8 col-lg-8 col-centered">
    <div class="card">
      <div class="card-header card-header-tabs card-header-primary">
        <div class="nav-tabs-navigation">
          <div class="nav-tabs-wrapper">
            <span class="nav-tabs-title"><%= @list.name %></span>
          </div>
        </div>
      </div>
      <div class="row justify-content-center">
        <div class="col-md-8">
          <div class="form-group">
          </div>
        </div>
      </div>
      <div class="card-body">
        <div class="tab-content">
          <div class="tab-pane active" id="LISTNAME">
            <table class="table">
              <tbody>
              <% @list.items.each do |item| %>
                <tr>
                  <td>
                    <div class="form-check">
                      <label class="form-check-label">
                        <%= form_for([@list, item]) do |f| %>
                          <%= f.check_box :status, :class => "toggle", :checked => (true if item.complete?) %>
                        <% end %>
                      </label>
                    </div>
                  </td>
                  <td>
                    <%= item.description %>
                  </td>
                  <td class="td-actions text-right">
                    <button type="button" rel="tooltip" title="Edit Task" class="btn btn-primary btn-link btn-sm">
                      <i class="material-icons">edit</i>
                    </button>
                    <button type="button" rel="tooltip" title="Remove" class="btn btn-danger btn-link btn-sm">
                      <i class="material-icons">close</i>
                    </button>
                  </td>
                </tr>
              <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>