config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth', registrations: 'users/registrations' }
  devise_scope :user do
    match '/session/user', to: 'devise/sessions#create', via: :post
    match '/users/sign_up', to: 'devise/registrations#create', via: :post
    root to: "devise/sessions#new"
  end
  resources :users do
    resources :homes do
      resources :lists do
        resources :items
      end
    end
  end
  resources :homes
  resources :lists do
    resources :items
  end
  resources :homes do
    resources :bridges
  end
  resources :bridges do
    resources :groups do
      resources :scenes
    end
  end
  resources :groups do
    resources :scenes
  end
  resources :scenes
  resources :users do
    resources :homes do
      resources :pets
    end
  end
  resources :pets
  resources :static
  resources :admin, only: [:index]
  get '/logout', to: 'remove#destroy'
end

app/models/home.rb
class Home < ApplicationRecord
  belongs_to :user
  has_one :pet
  has_many :lists
  has_many :items, through: :lists
  has_many :bridges
  accepts_nested_attributes_for :pet
  accepts_nested_attributes_for :lists
  validates_format_of :zip_code,
                      with: /\A\d{5}-\d{4}|\A\d{5}\z/,
                      message: "should be 12345 or 12345-1234",
                      allow_blank: false
  validates :name, uniqueness: {scope: :user_id}
  validates_presence_of :name, :state, :street, :city
  geocoded_by :address
  after_validation :geocode
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :authenticate_user!

  def new
    @user = current_user
    @home = Home.new
    @states = helpers.state_list

  end

  def create
    @user = current_user
    @states = helpers.state_list
    @home = Home.create(home_params)
    @home.build_pet
    if @home.save
      helpers.address(@home.id)
      helpers.timezone(@home.id)
      helpers.create_list_widget(@home.id)
      helpers.create_weather_widget(@home.id) if @home.weather_widget?
      helpers.create_bridges(@home.id) if @home.hue_widget?
      helpers.quote_of_the_day(@home.id)
      redirect_to user_home_path(current_user, @home)
    else
      render 'index'
    end
  end

  def show
    @user = User.find(params[:user_id])
    @home = Home.find(params[:id])
    @weather_widget = WeatherWidget.find(@home.weather_widget_id) if @home.weather_widget?
    helpers.need_weather_update(@home.id) if @home.weather_widget?
    @forecast = helpers.find_current_forecast(@weather_widget.id) if @home.weather_widget?
    @today = helpers.find_current_day(@weather_widget.id) if @home.weather_widget?
    @pet = Pet.find_by_home_id(@home.id)
    @lists = @home.lists
    @new_item = Item.new
    @bridges = @home.bridges
    @groups = Group.where(bridge_id: @bridges)
    if @home.user_id != current_user.id || @user.id != current_user.id
      redirect_to '/403'
    end
  end

  def index
    @user = current_user
    @home = Home.new
    @states = helpers.state_list
  end

  def edit
    @home = Home.find(params[:id])
    @user = current_user
    @states = helpers.state_list
  end

  def update
    @home = Home.find(params[:id])
    @home.update_attributes(home_params)
    helpers.create_weather_widget(@home.id) if @home.weather_widget?
    redirect_to user_home_path(current_user, @home)
  end

  def destroy
    @home = Home.find(params[:id])
    @home.destroy
      redirect_to user_homes_path(current_user)
  end

  private

  def home_params
    params.require(:home).permit(:name, :zip_code, :street, :city, :state, :weather_widget, :pet_widget, :home_widget, :hue_widget, :calendar_widget, :list_widget, :user_id,
                                 lists_attributes: [
                                     :name
                                 ],
                                 pet_attributes: [
                                     :feeding,
                                     :id,
                                     :bathroom_break,
                                     :walk,
                                     :pet_type,
                                     :home_id
                                 ]
    )
  end

end

app/helpers/homes_helper.rb
module HomesHelper
  # creates list of states to select from during home creation process
  def state_list
    state_codes = []
    us = Carmen::Country.coded('US')
    states = us.subregions.typed('state')
    states.each do |state|
      individual_code = state.code
      state_codes << individual_code
    end
    return state_codes
  end

  # takes individual address fields and combines them into one address field in the home table
  def address(home_id)
    @home = Home.find(home_id)
    location = [@home.street, @home.city, @home.state, @home.zip_code].compact.join(', ')
    @home.address = location
    @home.save
    return location
  end

  def timezone(home_id)
    @home = Home.find(home_id)
    zone = Timezone.lookup(@home.latitude, @home.longitude)
    @home.timezone = zone
    @home.save
  end

  def quote_of_the_day(home_id)
    @home = Home.find(home_id)
    path = "https://quotes.rest/qod?language=en"
    uri = URI.parse(path)
    response = Net::HTTP.get(uri)
    quote_data = JSON.parse(response)
    quote = quote_data['contents']['quotes'][0]['quote']
    author = quote_data['contents']['quotes'][0]['author']
    @home.update(quote: quote)
    @home.update(quote_author: author)
  end

end

app/views/homes/_calendar_widget.html.erb
  <div class="card card-stats">
    <div class="card-header card-header-info card-header-icon">
      <div class="card-icon">
        <i class="material-icons">calendar_today</i>
      </div>
      <h4 class="card-title">Calendar</h4>
      <br><br>
      <div class="col-md-12">
        <iframe src="https://calendar.google.com/calendar/embed?height=400&amp;wkst=1&amp;bgcolor=%234285F4&amp;ctz=America%2FLos_Angeles&amp;src=Y3BlOWQzdm9qdmVqNjg3ZXVrNzk3aTJiNGdAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ&amp;color=%23009688&amp;showTz=0&amp;showCalendars=0&amp;showPrint=0&amp;mode=MONTH&amp;showNav=1&amp;showTitle=0" style="border-width:0" frameborder="0" scrolling="no"></iframe>
      </div>
    </div>
    <div class="card-footer">
      <div class="stats">
        <i class="material-icons">update</i> Just Updated
      </div>
      <div class="stats">
        <i class="material-icons">add</i>
        <a href="#" onclick="popupCenter({url: 'https://calendar.google.com/calendar?cid=Y3BlOWQzdm9qdmVqNjg3ZXVrNzk3aTJiNGdAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ', title: 'Calendar', w: 900, h: 900});"> New Event</a>
      </div>
    </div>
  </div>

app/views/homes/_existing_homes.html.erb
<div class="row">
  <div class="col-md-8 col-lg-8 col-centered">
    <div class="card">
      <div class="card-header card-header-primary">
        <h3 class="card-title ">Existing Homes</h3>
        <h5>Select an existing home to view further details, edit information, or change widget settings.</h5>
      </div>
      <div class="card-body">
        <div class="table-responsive">
          <table class="table">
            <thead class=" text-primary">
            <th>ID</th>
            <th>Name</th>
            <th>Address</th>
            <th>Home Settings</th>
            <th></th>
            <th></th>
            </thead>
            <tbody>
            <% @user.homes.each do |home| %>
              <tr>
                <td><%= home.id %></td>
                <td><%= home.name %></td>
                <td><%= home.address %></td>
                <td><%= button_to "Edit Home", edit_user_home_path(current_user, home.id), method: :get, data: {turbolinks: 'false'}, class: "btn btn-sm btn-primary" %></td>
                <td><%= button_to "Delete", home, method: :delete, data: {confirm: "Are you sure? This cannot be undone."}, class: "btn btn-sm btn-danger" %></td>
                <td><%= link_to "Go to Dashboard", user_home_path(current_user, home.id), data: {turbolinks: 'false'} %></td>
              </tr>
            <% end %>
            </tbody>
          </table>
          <% if @user.homes.count == 0 %>
            <h5 class="text-warning">You haven't created a home yet! Get started below.</h5>
          <% end %>
        </div>
      </div>
      <br><br>
      <div class="card-header card-header-success">
        <h3 class="card-title">Create a New Home</h3>
        <h5>Fill in your house information and select your preferred widgets to generate your custom dashboard.</h5>
      </div>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/homes/_form.html.erb
<div class="card-body">
  <%= form_for [@user, @home] do |f| %>
    <% if @home.errors.any? %>
      <div id="error_explanation">
        <h4 class="text-danger">
          <%= pluralize(@home.errors.count, "error") %> prohibited this home from being saved:
        </h4>
        <ul>
          <% @home.errors.full_messages.each do |message| %>
            <li class="text-danger font-weight-bold"><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <h4><b><u>Home Information</u></b></h4>
    <div class="row">
      <div class="col-md-8 col-lg-8">
        <div class="form-group">
          <%= f.hidden_field :user_id, value: "#{@user.id}" %>
          <%= f.label :name, "Home Name", class: "bmd-label-floating" %>
          <%= f.text_field :name, class: "form-control", :required => true, placeholder: "ex - Kerbo Family, The West Home" %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-8 col-lg-8">
        <div class="form-group">
          <%= f.label :street, "Street", class: "bmd-label-floating" %>
          <%= f.text_field :street, class: "form-control", :required => true %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :city, "City", class: "bmd-label-floating" %>
          <%= f.text_field :city, class: "form-control", :required => true %>
        </div>
      </div>

      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :zip_code, "Zip Code", class: "bmd-label-floating" %>
          <%= f.number_field :zip_code, class: "form-control", :required => true %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-4">
        <div class="form-group">
          <%= f.label :state, "State", class: "bmd-label" %><br>
          <%= f.select :state, options_for_select(@states, @home.state), {}, {class: "form-control", required: true, placeholder: "Select State"} %>
        </div>
      </div>
    </div>
    <br>

    <br>
    <h4><b><u>Widgets</u></b></h4>
    <h5 class="text-warning">Select widgets that you would like to show on your HomeBoard. Widgets can be added or
      removed as needed.</h5>
    <br>
    <div class="card">
      <br>
      <div class="row">
        <div class="col-md-12">
          <h5>Home</h5>
        </div>
      </div>
      <div class="row">
        <div class="col-md-2">
          <div class="form-group">
            <%= f.hidden_field :home_widget, value: "false" %>
            <label class="switch">
              <%= f.check_box :home_widget, {class: "form-check-input"}, true, false %>
              <span class="light-switch round"></span>
            </label>
          </div>
        </div>
        <div class="col">
          <p>Displays the home name, a clock, current date, and the quote of the day.</p>
        </div>
        <div class="col">
          <%= image_tag("home_widget.png", class: "img-fluid") %>
        </div>
      </div>
      <br>
    </div>
    <div class="card">
      <br>
      <div class="row">
        <div class="col-md-12">
          <h5>Weather</h5>
        </div>
      </div>
      <div class="row">
        <div class="col-md-2">
          <div class="form-group">
            <%= f.hidden_field :weather_widget, value: "false" %>
            <label class="switch">
              <%= f.check_box :weather_widget, {class: "form-check-input"}, true, false %>
              <span class="light-switch round"></span>
            </label>
          </div>
        </div>
        <div class="col">
          <p>Displays current weather data and a 5-day weather forecast based on the location of your home.</p>
        </div>
        <div class="col">
          <%= image_tag("weather_widget.png", class: "img-fluid") %>
        </div>
      </div>
      <br>
    </div>
    <div class="card">
      <br>
      <div class="row">
        <div class="col-md-12">
          <h5>Calendar</h5>
        </div>
      </div>
      <div class="row">
        <div class="col-md-2">
          <div class="form-group">
            <%= f.hidden_field :calendar_widget, value: "false" %>
            <label class="switch">
              <%= f.check_box :calendar_widget, {class: "form-check-input"}, true, false %>
              <span class="light-switch round"></span>
            </label>
          </div>
        </div>
        <div class="col">
          <p>Displays an embedded Google calendar of your choice and includes a function to add events to the
            calendar.</p>
        </div>
        <div class="col">
          <%= image_tag("calendar_widget.png", class: "img-fluid") %>
        </div>
      </div>
      <br>
    </div>
    <div class="card">
      <br>
      <div class="row">
        <div class="col-md-12">
          <h5>Pets</h5>
        </div>
      </div>
      <div class="row">
        <div class="col-md-2">
          <div class="form-group">
            <%= f.hidden_field :pet_widget, value: "false" %>
            <label class="switch">
              <%= f.check_box :pet_widget, {class: "form-check-input"}, true, false %>
              <span class="light-switch round"></span>
            </label>
          </div>
        </div>
        <div class="col">
          <p>Provides 2 status trackers to keep tabs on actions needed for your pets, such as feeding and walking.</p>
        </div>
        <div class="col">
          <%= image_tag("pet_widget.png", class: "img-fluid") %>
        </div>
      </div>
      <br>
    </div>
    <div class="card">
      <br>
      <div class="row">
        <div class="col-md-12">
          <h5>List</h5>
        </div>
      </div>
      <div class="row">
        <div class="col-md-2">
          <div class="form-group">
            <%= f.hidden_field :list_widget, value: "false" %>
            <label class="switch">
              <%= f.check_box :list_widget, {class: "form-check-input"}, true, false %>
              <span class="light-switch round"></span>
            </label>
          </div>
        </div>
        <div class="col">
          <p>Allows for creation and displays of lists. You can create as many lists as you need.</p>
        </div>
        <div class="col">
          <%= image_tag("list_widget.png", class: "img-fluid") %>
        </div>
      </div>
      <br>
    </div>
    <div class="card">
      <br>
      <div class="row">
        <div class="col-md-12">
          <h5>Philips Hue</h5>
        </div>
      </div>
      <div class="row">
        <div class="col-md-2">
          <div class="form-group">
            <%= f.hidden_field :hue_widget, value: "false" %>
            <label class="switch">
              <%= f.check_box :hue_widget, {class: "form-check-input"}, true, false %>
              <span class="light-switch round"></span>
            </label>
          </div>
        </div>
        <div class="col">
          <p>Displays controls for any lights, groups (rooms), and scenes you have set up with Philips Hue. A Hue bridge
            and bulbs are <i>required</i> for this widget to function.</p>
        </div>
        <div class="col">
          <%= image_tag("hue_widget.png", class: "img-fluid") %>
        </div>
      </div>
      <br>
    </div>
    <div class="row">
      <br><br>
      <div class="col-md-12 pull-right">
        <%= f.submit class: "btn btn-primary pull-right" %>
      </div>
    </div>
    <div class="clearfix"></div>
  <% end %>
</div>

app/views/homes/_home_widget.html.erb
  <div class="card card-stats">
    <div class="card-header card-header-warning card-header-icon">
      <div class="card-icon">
        <i class="material-icons">home</i>
      </div>
      <h1 class="card-title" id="time"></h1>
      <h3 class="card-title"><%= Date.today.strftime('%A %B %d, %Y') %></h3>
      <br><br>
      <p class="font-italic text-center text-success">Quote of the Day</p>

      <blockquote class="h4 blockquote text-center">
        <p class="mb-0">"<%= @home.quote %>"</p>
        <footer class="blockquote-footer"><%= @home.quote_author %></footer>
      </blockquote>
    </div>
    <div class="card-footer">
      <div class="stats">
        <i class="material-icons">format_paint</i>
        <a href="<%= edit_user_home_path(current_user, @home) %>">Home Settings</a>
      </div>
    </div>
  </div>

<script>
    var interval = setInterval(timestamphome, 1000);

    function timestamphome(){
        var date;
        date = new Date();

        var time = document.getElementById('time');
        time.innerHTML = date.toLocaleTimeString([], {hour: '2-digit', minute:'2-digit'});

    }
</script>

app/views/homes/_hue_widget.html.erb
<% @bridges.each do |bridge| %>

  <div class="card card-stats">
    <div class="card-header card-header-info card-header-icon">
      <div class="card-icon">
        <i class="material-icons">highlight</i>
      </div>
      <h4 class="card-title">Light Control</h4>
    </div>
    <div class="card-body text-left">
      <% if bridge.username == nil %>
        <br>
        <p class="text-center h5">Connect HomeBoard to your Hue Bridge to finish setup.
          <br><%= link_to "I'm ready, let's do this!", edit_home_bridge_path(@home, bridge.id) %></p>
      <% else %>
        <% bridge.groups.order("name ASC").each do |group| %>
          <div class="accordion" id="accordion<%= group.id %>">
            <div class="hue-group" id="hue-widget">
              <div class="card-header" id="heading<%= group.id %>">
                <div class="row">
                  <div class="col-3">
                    <%= form_for [bridge, group], remote: true do |f| %>
                      <%= f.hidden_field :state, value: "false" %>
                      <label class="switch">
                        <%= f.check_box :state, {id: "customSwitch#{group.id}"}, true, false %>
                        <span class="light-switch round"></span>
                      </label>
                      <script>
                          $('#customSwitch<%=group.id %>').change(function () {
                              $("#edit_group_<%=group.id %>").submit();
                          });
                      </script>
                    <% end %>
                  </div>
                  <div class="col-6">
                    <h4>
                      <%= group.name %>
                      </a>
                    </h4>
                  </div>
                  <div class="col float-right">
                    <a href="#collapse<%= group.id %>" data-toggle="collapse" data-target="#collapse<%= group.id %>" aria-expanded="true" aria-controls="collapse<%= group.id %>">
                      Scenes
                    </a>
                  </div>
                </div>
              </div>
              <% group.scenes.each do |scene| %>
                <div id="collapse<%= group.id %>" class="collapse" aria-labelledby="heading<%= group.id %>" data-parent="#accordion<%= group.id %>">
                  <div class="card-body text-left">
                    <div class="custom-control custom-switch">
                      <%= form_for [scene], remote: true do |f| %>
                        <%= f.check_box :name, {checked: current_scene?(group.scene, scene.identifier), id: "sceneSwitch#{scene.id}"} %>
                        <%= f.label :name, scene.name, for: "sceneSwitch#{scene.id}" %>
                        <script>
                            $('#sceneSwitch<%=scene.id %>').change(function () {
                                $("#edit_scene_<%=scene.id %>").submit();
                            });
                        </script>
                      <% end %>
                    </div>
                  </div>
                </div>
              <% end %>
              <%= form_for [bridge, group], remote: true, :html => {id: "edit_range_#{group.id}", class: "edit_range_#{group.id}"} do |f| %>
                <%= f.range_field :brightness, {class: "slider", id: "myRange#{group.id}", value: "#{group.brightness}", min: "0", max: "254"} %>
              <% end %>
              <script>
                  $('#myRange<%= group.id %>').change(function () {
                      $("#edit_range_<%=group.id %>").submit();
                  });
              </script>
            </div>
          </div>
          <br>
        <% end %>
      <% end %>
    </div>
    <div class="card-footer">
    </div>
  </div>
<% end %>

app/views/homes/_list_widget.html.erb
<% @lists.each do |list| %>

    <div class="card card-stats">
      <div class="card-header card-header-icon card-header-primary">
        <div class="card-icon">
          <i class="fas fa-list-alt"></i>
        </div>
        <h4 class="card-title"><%= list.name %></h4>
        <% if list.name == "" %>
          <% name = "Default List" %>
          <h4 class="card-title"><%= name %></h4>
        <% end %>
        <div class="card-body">
          <div class="col-md-12 col-sm-12">
            <div class="form-group">
              <br>
              <% if list.name == "" %>
                <h5 class="text-center"><%= 'This is a default list created for you, you should' %>
                  <%= link_to "change the name" + '.', user_home_lists_path(current_user, @home), data: {turbolinks: 'false'} %>
                </h5>
              <% end %>
              <br>
              <%= form_for [@user, @home, list, @new_item], remote: true do |f| %>
                <div class="row">
                  <div class="col-md-8">
                    <%= f.text_field :description, :class => "form-control text-center", required: true, :placeholder => (@new_item.errors.full_messages_for(:description).first || "Enter a new item..."), id: "add-item" %>
                  </div>
                  <div class="col-md-4 float-right">
                    <button type="submit" rel="tooltip" class="btn-sm" id="add-item">
                      <i class="fas fa-plus-square fa-2x" id="add-item"></i>
                    </button>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
        <div class="card-body">
          <div class="tab-content">
            <div class="tab-pane active" id="LISTNAME">
              <table class="table">
                <tbody>
                <% list.items.order("status asc").each do |item| %>
                  <tr>
                    <td>
                    <%= form_for [list, item], remote: true do |f| %>
                      <div class="form-check">
                        <div class="col-md-11 text-left">
                          <%= f.check_box :status, :checked => (true if item.complete?), class: "toggle" %>
                          <%= f.label item.description, id: "strikethrough" %>
                          <%= f.submit :style => "display: none" %>
                        </div>
                    <% end %>
                    </div>
                    </td>


                    <td class="td-actions">
                      <%= form_for [list, item], method: :delete, remote: true do |f| %>
                        <button type="submit" rel="tooltip" class="btn-sm" id="remove-item">
                          <i class="fas fa-times-circle fa-lg" id="remove-item"></i>
                        </button>
                      <% end %>
                    </td>
                    </tr>
                <% end %>
                </tbody>
                </table>
                </div>
        </div>
      </div>
    </div>
    <div class="card-footer">
      <div class="stats">
        <i class="material-icons">settings</i>
        <a href="<%= user_home_lists_path(current_user, @home) %>">Settings</a>
      </div>
      <div class="stats">
        <i class="material-icons">add</i>
        <a href="<%= user_home_lists_path(current_user, @home) %>">New List</a>
      </div>
    </div>
  </div>
  <script>
      $(function () {
          $("input.toggle").on("change", function () {
              $(this).parents("form").trigger("submit")
          })
      });
  </script>
<% end %>

app/views/homes/_pet_widget.html.erb
  <div class="card card-stats">
    <div class="card-header card-header-danger card-header-icon">
      <div class="card-icon">
        <i class="material-icons">pets</i>
      </div>
      <h3 class="card-title">Pets</h3><br><br>
      <div class="row">
        <div class="col-md-12">
          <%= form_for [@pet], remote: true do |pet| %>
              <div class="form-group">
                <div class="row">
                  <div class="col-md-12 col-lg-12">
                    <div class="col-md-12">
                    <% if @pet.status1_time.nil? %>
                      <p class="text-center h5">The pets haven't been fed today, they must be starving!</p>
                      <% else %>
                      <p class="text-center h5"><%= @pet.status1_message %> <b class="text-success h3 font-weight-bold"><%= @pet.status1_time %></b> today.</p>
                      <% end %>
                      <%= pet.button "#{@pet.status1}", class: "btn btn-sm btn-primary pull-right", id: "pet-button1", value: "1" %>
                    </div>
                  </div>
                </div>
                <br>
                <div class="row">
                  <div class="col-md-12 col-lg-12">
                    <div class="col-md-12">
                    <% if @pet.status2_time.nil? %>
                      <p class="text-center h5">The dogs haven't been let outside today, they seem antsy.</p>
                    <% else %>
                      <p class="text-center h5"><%= @pet.status2_message %> <b class="text-success h3 font-weight-bold"><%= @pet.status2_time %></b> today.</p>
                    <% end %>
                      <%= pet.button "#{@pet.status2}", class: "btn btn-sm btn-primary pull-right", id: "pet-button2", value: "2" %>
                    </div>
                  </div>
                </div>
          <% end %>
        </div>
      </div>
    </div>
    </div>
    <div class="card-footer">
      <div class="stats">
        <i class="material-icons">settings</i> <%=link_to "Settings", edit_user_home_pet_path(@user, @home, @pet) %>
      </div>
    </div>

</div>

app/views/homes/_weather_widget.html.erb
  <div class="card card-stats" id="weather_widget">
    <div class="card-header card-header-success card-header-icon">
      <div class="card-icon">
        <img class="d-md-block mx-auto" src="<%= image_path("icons/#{@today.icon}.svg") %>" alt="">
      </div>
      <h4 class="card-title"><%= @home.city %>, <%= @home.state %></h4>
      <h5 class="card-title"><%= @today.current_temp.round %>°</h5>
      <p class="card-title" style="font-style: italic; font-size: small">Feels like <%= @today.feels_like.round %>°</p>
      <h4 class="card-title"></h4>
      <br>

      <div class="row">
        <div class="col-md-12">
          <div class="row">
            <div class="weather col-md-4">
              <img class="d-md-block mx-auto" id="weather-img" src="<%= image_path('icons/temp_cold.svg') %>" alt="">
              <p class="card-category" style="text-align: center"><%= @today.temp_high.round %>°/<%= @today.temp_low.round %>°</p>
            </div>
            <div class="weather col-md-4">
              <p class="card-category" style="text-align: center; margin-bottom: 25%; margin-top: 25%"><%= @today.summary %></p>
            </div>
            <%unless !@today.precipitation_type.nil? %>
              <div class="weather col-md-4">
                <img class="d-md-block mx-auto" id="weather-img" src="<%= image_path('icons/precip_chance.svg') %>" alt="">
                <p class="card-category" style="text-align: center">0%</p>
              </div>
              <% end %>
            <%unless @today.precipitation_type.nil? %>
            <div class="weather col-md-4">
              <img class="d-md-block mx-auto" id="weather-img" src="<%= image_path('icons/precip_chance.svg') %>" alt="">
              <p class="card-category" style="text-align: center"><%= @today.precipitation_chance %>%</p>
            </div>
            <div class="weather col-md-4">
              <img class="d-md-block mx-auto" id="weather-img" src="<%= image_path("icons/#{@today.precipitation_type}.svg") %>" alt="">
              <p class="card-category" style="text-align: center"><%= @today.precipitation_type.titleize %></p>
            </div>
              <% end %>
            <div class="weather col-md-4">
              <img class="d-md-block mx-auto" id="weather-img" src="<%= image_path('icons/sunrise.svg') %>" alt="">
              <p class="card-category" style="text-align: center"><%= @today.sunrise %></p>
            </div>
            <div class="weather col-md-4">
              <img class="d-md-block mx-auto" id="weather-img" src="<%= image_path('icons/sunset.svg') %>" alt="">
              <p class="card-category" style="text-align: center"><%= @today.sunset %></p>
            </div>
          </div>
          <br>
          <div class="row">
            <% @forecast.each do |day| %>
            <div class="col weather">
              <p class="card-category h6" style="text-align: center; font-size: small"><%= day.date %></p>
              <img class="d-md-block mx-auto" id="weather-img" style="height: 20px;" src="<%= image_path("icons/#{day.icon}.svg") %>" alt="">
              <p class="card-category h6" style="text-align: center; font-size: x-small"><%= day.temp_high.round %>°/<%= day.temp_low.round %>°</p>
            </div>
              <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="card-footer">
      <div class="stats">
        <i class="material-icons">date_range</i> Updated: <%= @weather_widget.updated_at.strftime('%l:%M %P') %>
      </div>
    </div>
  </div>

app/views/homes/edit.html.erb
<div class="content">
  <div class="container-fluid">
    <a href="javascript:history.back()">< Return to Previous Page</a>
    <div class="row">
      <div class="col-md-8 col-lg-8 col-centered">
        <div class="card">
          <div class="card-header card-header-primary">
            <h3 class="card-title">Edit Home Details</h3>
          </div>
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/homes/index.html.erb
<div class="content">
  <div class="container-fluid">
    <a href="javascript:history.back()">< Return to Previous Page</a>
    <div class="col-md-12">
    <% if @user.homes.count == 0 %>
      <h2 style="color: white">Welcome to HomeBoard!</h2>
        <br>
      <h3 style="color: white">Get started by creating your first home. Once you create a home, you will have access to a custom dashboard for your house.</h3>
    <%end %>
    </div>
    <br>
      <%= render 'existing_homes' %>
      </div>
</div>