config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth', registrations: 'users/registrations' }
  devise_scope :user do
    match '/session/user', to: 'devise/sessions#create', via: :post
    match '/users/sign_up', to: 'devise/registrations#create', via: :post
    root to: "devise/sessions#new"
  end
  resources :users do
    resources :homes do
      resources :lists do
        resources :items
      end
    end
  end
  resources :homes
  resources :lists do
    resources :items
  end
  resources :homes do
    resources :bridges
  end
  resources :bridges do
    resources :groups do
      resources :scenes
    end
  end
  resources :groups do
    resources :scenes
  end
  resources :scenes
  resources :users do
    resources :homes do
      resources :pets
    end
  end
  resources :pets
  resources :static
  resources :admin, only: [:index]
  get '/logout', to: 'remove#destroy'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HomeBoard</title>
    <%= csrf_meta_tags %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta content='width=device-width, initial-scale=1.0, shrink-to-fit=no' name='viewport' />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" %>
  </head>
  <body data-turbolinks="false">
  <header>
    <nav class="navbar navbar-expand-md bg-dark navbar-dark">
      <!-- Brand -->
      <a class="navbar-brand" href="<%= user_homes_path(current_user) %>">HomeBoard</a>
      <!-- Toggler/collapsibe Button -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
      </button>
      <!-- Navbar links -->
      <div class="collapse navbar-collapse text-center" id="collapsibleNavbar">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Manage
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <% if @user.admin? %>
                <a class="dropdown-item" href="<%= admin_index_path %>">Admin</a>
                <%else %>
                <% unless @home.id.nil? %>
                <a class="dropdown-item" href="<%= edit_user_home_path(current_user, @home) %>">Home Settings</a>
                <% end %>
                <%end %>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="<%= user_homes_path(current_user) %>">My Homes</a>
            </div>
          </li>
          <a class="nav-link" href="<%= destroy_user_session_path %>">Logout <span class="sr-only">(current)</span></a>
        </ul>
      </div>
    </nav>
  </header>
 <% flash.each do |name, message| %>
      <% if name =="error" %>
        <div class="alert alert-danger" role="alert">
        <%= message %>
        </div>
      <% else %>
        <div class="alert alert-success" role="alert">
          <%= message %>
        </div>
      <% end %>
    <% flash.discard %>
    <% end %>
      <!-- End Navbar -->
    <%= yield %>
    <footer class="footer">
      <div class="container">
        <nav class="text-center">
        </nav>
        <div class="text-center">
          &copy; HomeBoard
          <script>
              document.write(new Date().getFullYear())
          </script>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/layouts/static.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>HomeBoard</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<style>
  .footer {
    position: absolute;
    bottom: 0;
    width: 100%;
    height: 60px;
    line-height: 60px;
    background: #007bff;
    background: linear-gradient(to right, #0062E6, #33AEFF);
    background-size: cover;
    background-repeat: no-repeat;
    font-family: 'Numans', sans-serif;
    z-index: 10;
    color: white;
  }

  html,body{
    background: #007bff;
    background: linear-gradient(to right, #0062E6, #33AEFF);
    background-size: cover;
    background-repeat: no-repeat;
    font-family: 'Numans', sans-serif;
    margin: 0;
    height: 100vh;
    overflow: hidden;
  }

  html *
  {
    font-family: "Helvetica Neue", Helvetica, Arial, Sans-Serif
  }

  .content {
    overflow-y: auto;
    padding: 0px;
    margin-top: 10px;
  }
  nav.navbar-light li.nav-item a.nav-link {
    color: white;
  }

  .container{
    height: 100vh;
    align-content: center;
  }

  .card{
    height: 500px;
    margin-top: auto;
    margin-bottom: auto;
    width: 400px;
    background-color: rgba(0,0,0,0.4) !important;
  }

  .social_icon span{
    font-size: 60px;
    margin-left: 10px;
    color: #FFFFFF;
  }

  .social_icon span:hover{
    color: white;
    cursor: pointer;
  }

  .card-header h3{
    color: white;
  }

  .social_icon{
    position: absolute;
    right: 20px;
    top: -45px;
  }

  .input-group-prepend span{
    width: 50px;
    background-color: #FFFFFF;
    color: black;
    border:0 !important;
  }
  .or-seperator {
    margin: 20px 0 10px;
    text-align: center;
    border-top: 1px solid #ccc;
  }

  .or-seperator i {
    padding: 0 10px;
    background: rgba(0,0,0) !important;
    position: relative;
    top: -11px;
    color: white;
    z-index: 1;
  }

  input:focus{
    outline: 0 0 0 0  !important;
    box-shadow: 0 0 0 0 !important;

  }

  .remember{
    color: white;
  }

  .remember input
  {
    width: 20px;
    height: 20px;
    margin-left: 15px;
    margin-right: 5px;
  }


  .login_btn{
    color: black;
    background-color: #FFFFFF;
    width: 100px;
  }

  .login_btn:hover{
    color: black;
    background-color: white;
  }

  .links{
    color: white;
  }

  .links a{
    margin-left: 4px;
  }

  .btn-google {
    color: white;
    background-color: #ea4335;
    width: 60%;
  }
</style>
</head>

<body data-turbolinks="false">

<header>
  <nav class="navbar navbar-expand-lg navbar-light" style="color:white">
    <a class="navbar-brand" href="/" style="color:white">HomeBoard</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-1 text-right" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto flex-nowrap">
        <li class="nav-item">
          <a class="nav-link" href=<%= new_user_registration_path %>><span class="glyphicon glyphicon-log-in"></span> Sign Up</a></li>
        </li>
        <li class="nav-item">
          <a class="nav-link" href=<%= user_session_path %>><span class="glyphicon glyphicon-log-in"></span> Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link <% unless user_signed_in? %><%= "disabled" %><% end %>" href=<%= destroy_user_session_path %>><span class="glyphicon glyphicon-log-in"></span> Logout</a>
        </li>
      </ul>
    </div>
  </nav>
</header>
<% flash.each do |name, message| %>
  <% if name =="error" %>
    <div class="alert alert-danger" role="alert">
      <%= message %>
    </div>
  <% else %>
    <div class="alert alert-success" role="alert">
      <%= message %>
    </div>
  <% end %>
<% end %>

  <%= yield %>

<footer class="footer navbar-fixed-bottom text-center">
  &copy; HomeBoard
  <script>
      document.write(new Date().getFullYear())
  </script>
</footer>

</body>
</html>